version: '3.1'

services:

  db:
    container_name: neo4j
    image: neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/ananke
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
